name: workervgps
description: a app for worker Vgps

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  toast: ^0.1.5
  sqflite: ^1.3.0
  dio: ^3.0.9
  path: ^1.6.4
  path_provider: 2.0.1
  http: ^0.12.1
  file_picker: ^5.2.3
  flutter_pdfview: ^1.2.1
  provider: 4.3.3
  slider_button: ^0.0.32
  generic_bloc_provider: ^1.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_datetime_picker: ^1.3.8

flutter:
  uses-material-design: true

  assets:
    - LogoTransparente.png
    - resultado.png
    - error.png
    - Pagos_Vgps.png
    - Cerrar_Ventas.png
    - Registro_Contable.png
    - Facturacion_Vgps.png
    - buscar_app1.png
    - FA2102-12109.pdf
    - pngReceiver.png
    - sinDocumento.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf